models/story.py
from . import Mongua


class Story(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('story_name', str, ''),
        ('title', str, ''),
        ('content', str, ''),
        ('page', int, -1),
    ]

routes/story.py
from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    url_for,
)
from models.story import Story
from models.user import User
from . import current_user
from utils import (
    style,
    format_content,
)
import json

main = Blueprint('story', __name__)


@main.route('/')
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    story_name = 'dpcq'
    if u.dpcq == -1:
        s = Story.find_by(story_name=story_name, page=1)
    else:
        s = Story.find_by(story_name=story_name, page=u.dpcq)
    tag_story = 'dpcq'
    return render_template('story/story_index.html', title=s.title,
                           content=s.content, style_dldl='', style_dpcq=style[1], tag_story=tag_story)


@main.route('/new')
def new():
    u = current_user()
    if u.id != 1:
        return redirect(url_for('index.homepage'))
    return render_template('story/story_add.html')


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    if u.id != 1:
        return redirect(url_for('index.homepage'))
    form = dict(request.form)
    form['content'] = format_content(form['content'])
    Story.new(form)
    return redirect(url_for('story.index'))


@main.route('/api/dpcq/next')
def dpcq_next():
    u = current_user()
    if u.dpcq == 1912:
        page = 1912
        s = Story.find_by(story_name='dpcq', page=page)
    elif u.dpcq == -1:
        page = 2
        s = Story.find_by(story_name='dpcq', page=page)
    else:
        page = u.dpcq + 1
        s = Story.find_by(story_name='dpcq', page=page)
    user_update = {
        'dpcq': page,
    }
    User.update(user_update, id=u.id)
    form = {
        'title': s.title,
        'content': s.content,
    }
    return json.dumps(form)


@main.route('/api/dpcq/last')
def dpcq_last():
    u = current_user()
    if u.dpcq == -1 or u.dpcq == 1:
        page = 1
        s = Story.find_by(story_name='dpcq', page=page)
    else:
        page = u.dpcq - 1
        s = Story.find_by(story_name='dpcq', page=page)
    user_update = {
        'dpcq': page,
    }
    User.update(user_update, id=u.id)
    form = {
        'title': s.title,
        'content': s.content,
    }
    return json.dumps(form)


@main.route('/api/dldl/next')
def dldl_next():
    u = current_user()
    if u.dldl == 738:
        page = 738
        s = Story.find_by(story_name='dldl', page=page)
    elif u.dldl == -1:
        page = 2
        s = Story.find_by(story_name='dldl', page=page)
    else:
        page = u.dldl + 1
        s = Story.find_by(story_name='dldl', page=page)
    user_update = {
        'dldl': page,
    }
    User.update(user_update, id=u.id)
    form = {
        'title': s.title,
        'content': s.content,
    }
    return json.dumps(form)


@main.route('/api/dldl/last')
def dldl_last():
    u = current_user()
    if u.dldl == -1 or u.dldl == 1:
        page = 1
        s = Story.find_by(story_name='dldl', page=page)
    else:
        page = u.dldl - 1
        s = Story.find_by(story_name='dldl', page=page)
    user_update = {
        'dldl': page,
    }
    User.update(user_update, id=u.id)
    form = {
        'title': s.title,
        'content': s.content,
    }
    return json.dumps(form)


@main.route('/dldl')
def dldl_index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    story_name = 'dldl'
    if u.dldl == -1:
        s = Story.find_by(story_name=story_name, page=1)
    else:
        s = Story.find_by(story_name=story_name, page=u.dldl)
    tag_story = 'dldl'
    return render_template('story/story_index.html', title=s.title,
                           content=s.content, style_dldl=style[0], style_dpcq='', tag_story=tag_story)

templates/story/story_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <form action="{{ url_for('story.add') }}" method="post">
         <textarea rows="1" cols="8" name="page" placeholder="page"></textarea>
         <br>
         <textarea rows="5" cols="40" name="story_name" placeholder="story_name">dldl</textarea>
         <br>
         <textarea rows="5" cols="40" name="title" placeholder="title"></textarea>
         <br>
         <textarea rows="100" cols="100" name="content" placeholder="content"></textarea>
         <br>
         <button style="submit">button</button>
     </form>
</body>
</html>

templates/story/story_index.html
<!DOCTYPE html>
<html lang="Zh-CN" xmlns="http://www.w3.org/1999/html">
  <head>
	<meta charset="utf-8">
    <title>11-Text-Smoke</title>
    <link rel="stylesheet" href="/static/CSS/story.css">
  </head>
  <body>
  	<div class="tag">
		<section>
			<video loop="-1" src="/static/IMG/smoke.mp4" autoplay muted></video>
			<h1>
				<span>S</span>
				<span>T</span>
				<span>O</span>
				<span>R</span>
				<span>Y</span>
			</h1>
		</section>
	</div>
	<div class="story-title">
		<a href="{{ url_for('story.dldl_index') }}" style="{{ style_dldl }}">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
			<h3>斗罗大陆</h3>
			<p>唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆,这里没有魔法...</p>
		</a>
		<a href="{{ url_for('story.index') }}" style="{{ style_dpcq }}">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
			<h3>斗破苍穹</h3>
			<p>这里是属于斗气的世界，没有花俏艳丽的魔法，有的，仅仅是繁衍到巅峰的斗气！新书等级制度：斗者，斗师，大斗师，斗灵，斗王，斗皇，斗宗，斗尊，斗圣，斗帝...</p>
		</a>
	</div>
	<section class="story-content">
		<h2 class="js-title">{{ title }}</h2>
		<p class="js-content">{{ content | safe }}</p>
		<div class="btn">
		  <button class="button last">last</button>
		  <button class="button next">next</button>
  		</div>
	</section>
	<svg>
		<filter id="wavy">
			<feTurbulence x="0" y="0" baseFrequency="0.02" numOctaves="5" seed="2">
				<animate attributeName="baseFrequency" dur="60s" values="0.02;0.05;0.02" repeatCount="indefinite"/>
			</feTurbulence>
			<feDisplacementMap in="SourceGraphic" scale="30"/>
		</filter>
	</svg>
  	<input class="tag_story" type="hidden" value="{{ tag_story }}">
  </body>
  <script src="https://cdn.bootcss.com/jquery/3.5.0/jquery.js"></script>
  <script type="text/javascript" src="/static/JS/story.js"></script>
</html>