models/topic.py
from . import Mongua
from .reply import Reply
from utils import log
import redis
import logging
import json
from .user import User
ogger = logging.getLogger("website")


class RedisCache(object):
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def set(self, key, value):
        return RedisCache.redis_db.set(key, value)

    def get(self, key):
        return RedisCache.redis_db.get(key)


class Topic(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('user_id', int, -1),
        ('title', str, ''),
        ('content', str, ''),
        ('views', int, 0),
    ]
    should_update_all = True
    redis_cache = RedisCache()

    def save(self):              # Mongo的save方法为mongo的insert_one方法,new()方法会用到save这样就自动True了
        super().save()
        Topic.should_update_all = True

    @classmethod
    def delete(cls, id):
        t = super().delete(id)
        Topic.should_update_all = True
        return t

    @classmethod
    def get(cls, id):
        t = Topic.find_by(id=id)
        if t is None:
            return None
        form = {
            'views': t.views + 1
        }
        tt = Topic.new_update(form, id=id)
        return tt

    @classmethod
    def replies(cls, tid):
        return Reply.find_all(topic_id=tid)

    def user(self):
        return User.find_by(id=self.user_id)

    @classmethod
    def new_update(cls, form, **kwargs):
        t = super().update(form, **kwargs)
        Topic.should_update_all = True
        return t

    @classmethod
    def new_all(cls):
        if Topic.should_update_all:
            ts = Topic.all()
            if not ts:
                return ts
            t_list = []
            for t in ts:
                d = t.__dict__
                d.pop('_id')
                t_list.append(d)
            Topic.redis_cache.set('all_topic', json.dumps(t_list))
            Topic.should_update_all = False
            return ts
        d_list = json.loads(Topic.redis_cache.get('all_topic').decode('utf-8'))
        t_list = []
        for d in d_list:
            t_list.append(Topic.change(d))
        return t_list

    @classmethod
    def change(cls, d):
        topic = Topic()
        fields = Topic.__fields__.copy()
        fields.remove('_id')
        for f in fields:
            k, t, v = f
            if k in d:
                setattr(topic, k, t(d[k]))
            else:
                setattr(topic, k, v)
        return topic

routes/reply.py
from flask import (
    Blueprint,
    redirect,
    request,
    url_for,
)
from utils import format_content
import json
from models.topic import Topic
from models.reply import Reply

from . import current_user

main = Blueprint('reply', __name__)


@main.route('/api/all', methods=['GET'])
def all_reply():
    tid = int(request.args['topic_id'])
    rs = Topic.replies(tid)
    # replies = [r.__dict__ for r in rs]
    replies = []
    for r in rs:
        d = r.__dict__
        d.pop('_id')
        replies.append(d)
    return json.dumps(replies)            # 不能有_id.


@main.route('/api/add', methods=['POST'])
def add():
    form = json.loads(request.data.decode('utf-8'))
    form['content'] = format_content(form['content'])
    api_form = Reply.new(form).__dict__
    api_form.pop('_id')
    return json.dumps(api_form)

routes/topic.py
# coding=utf8
from flask import (
    Blueprint,
    redirect,
    abort,
    render_template,
    request,
    url_for,
)
from utils import (
    format_content,
    random_background,
)
import redis
from models.topic import (
    Topic,
)
from . import current_user
import uuid

main = Blueprint('topic', __name__)
token = dict()
redis_video_db = redis.StrictRedis(host='localhost', port=6379, db=0)
jump_video = True
jump_img = True


@main.route('/')
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    ts = Topic.new_all()
    ts.reverse()
    topic_background = random_background()
    return render_template('topic/topic_index.html', topics=ts, topic_background=topic_background)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    t = Topic.get(id)
    tid = id
    if u.id == t.user_id:
        display = "inline"
        key = "{}".format(uuid.uuid4())
        token[key] = u.username
        delete_background = random_background()
        return render_template('topic/detail.html', t=t, delete_background=delete_background,
                               display=display, token=key, id_user=u.id, tid=tid)
    else:
        display = "none"
        return render_template('topic/detail.html', t=t, display=display,
                               token='', id_user=u.id, tid=tid)


@main.route('/new')
def new():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    user_id = u.id
    return render_template('topic/new.html', uid=user_id)


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    if request.form['title'] == '':
        return redirect(url_for('topic.new'))
    form = dict(request.form)
    form['content'] = format_content(form['content'])
    Topic.new(form)
    return redirect(url_for('topic.index'))


@main.route('/delete')
def delete():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    tid = int(request.args['id'])
    validate_token = request.args['token']
    if token[validate_token] != u.username:
        return redirect(url_for('topic.index'))
    Topic.delete(tid)
    token.pop(validate_token)
    return redirect(url_for('topic.index'))


# 静态且不变的文件可以直接在程序启动时发给redis，在load路由只用get redis的数据就行.
# @main.route('/static')
# def load_video():
#     if request.args['file'] == 'bili2.mp4':
#         global jump_video
#         if jump_video:
#             with open('static/IMG/bili2.mp4', 'rb') as f:
#                 ff = f.read()
#                 redis_video_db.set('video', ff)
#             jump_video = False
#             return ff
#         return redis_video_db.get('video')
#     elif request.args['file'] == 'heart':
#         global jump_img
#         if jump_img:
#             with open('static/IMG/heart.png', 'rb') as f:
#                 ff = f.read()
#                 redis_video_db.set('img', ff)
#             jump_img = False
#             return ff
#         return redis_video_db.get('img')
#     else:
#         abort(404)

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <link rel="stylesheet" href="/static/CSS/detail.css">

</head>
<body>
        <div class="reveal">
            <span class="title">Blog</span>
        </div>
        <div class="blog-box">
            <span class="title-1">{{ t.title }}</span>
            <span class="description d-content">内容</span>
            <span class="content">{{ t.content | safe }}</span>
            <a class="btn" type="submit" style="display: {{ display }}; background: {{ delete_background }};" href="{{ url_for('topic.delete', id=t.id, token=token) }}">删除</a>
            <div class="replies_list">
                <span class="description d-comment">评论</span>
            </div>

            <div class="reply_content">
                <textarea class="content-2" data-uid="{{ id_user }}" data-tid="{{ t.id }}" rows="4" cols="30" placeholder="...输入评论"></textarea>
                <div class="button">
                    <ul></ul>
                    <button class="btn-reply" type="submit">提交</button>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            var backgroundSelector = {
                1: "#FCE6C9",
                2: "#708069",
                3: "#B03060",
                4: "#872657",
                5: "#BDFCC9",
                6: "#E3CF57",
                7: "#082E54",
                8: "#3D9140",
                9: "#A066D3",
                10: "#873324",
                11: "#FF7D40",
                12: "#33A1C9",
            }
            var ajax = function(method, path, data, responseCallback) {
            var r = new XMLHttpRequest()
            r.open(method, path, true)
            r.setRequestHeader('Content-Type', 'application/json')
            r.onreadystatechange = function() {
                if(r.readyState === 4) {
                    responseCallback(r.response)
                }
            }
            data = JSON.stringify(data)
            r.send(data)
            }

            var log = function() {
                console.log.apply(console, arguments)
            }

            var e = function(sel) {
                return document.querySelector(sel)
            }

            var apiAllReply = function(callback) {
                var method = 'GET'
                var path = '/reply/api/all?topic_id={{ tid }}'
                ajax(method, path, '', callback)
            }

            var apiAddReply = function(form, callback) {
                var method = 'POST'
                var path = '/reply/api/add'
                ajax(method, path, form, callback)
            }

            var template = function(r) {
                var randomBackground = backgroundSelector[parseInt(Math.random() * 12 + 1)]
                var m = `
                    <div class="cell uid-${r.user_id}" style="background: ${randomBackground};">
                        ${r.content}
                    </div>
                `
                return m
            }

            var insertReply = function(r) {
                var m = template(r)
                var list = e('.replies_list')
                list.insertAdjacentHTML('beforeend', m)
            }

            var loadReplies = function() {
                apiAllReply(function(response) {
                    var forms = JSON.parse(response)
                    for (var i = 0; i < forms.length; i++) {
                        var r = forms[i]
                        insertReply(r)
                    }
                })
            }

            var bindBtnEvent = function() {
                var btn = e('.btn-reply')
                btn.addEventListener('click', function() {
                    var content = e('.content-2')
                    var tid = parseInt(content.dataset.tid)
                    var uid = parseInt(content.dataset.uid)
                    var form = {
                        'topic_id': tid,
                        'user_id': uid,
                        'content': content.value,
                    }
                    apiAddReply(form, function(response) {
                        var r = JSON.parse(response)
                        insertReply(r)
                        content.value = ''
                    })
                })
            }

            var bindEvents = function() {
                bindBtnEvent()
            }

            var __main = function() {
                bindEvents()
                loadReplies()
            }
            __main()
        </script>
</body>
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Blog</title>
    <link rel="stylesheet" href="/static/CSS/new.css">
</head>
<body>
    <div class="reveal">
        <span class="title">Blog</span>
    </div>
    <div class="blog-box">
        <form action="{{ url_for('topic.add') }}" method="post">
            <div class="title-0">
                <input name="user_id" type="hidden" value="{{ uid }}">
                <input class="title-1" name="title" placeholder="标题不能为空">
            </div>
            <textarea class="content" name="content" rows="8" cols="80" placeholder="...内容..."></textarea>
            <button class="btn" type="submit">提交</button>
        </form>
    </div>
</body>
</html>

templates/topic/topic_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
    <link rel="stylesheet" href="/static/CSS/topic.css">

</head>
<body>
    <div class="reveal">
        <span class="title">Blog</span>
    </div>
    <a class="add" href="{{ url_for('topic.new') }}">New</a>
    <div class="blog-box">
        {% for t in topics %}
            <div class="topic" style="background: {{ topic_background }};">
                <div class="hehe">
                    <li class="tag"><i class="fa fa-thumbs-up"></i></li>
                    <a class="topic-title" href="{{ url_for('topic.detail', id=t.id) }}">
                        {{ t.title | truncate(8, True) }}
                    </a>
                    <span class="information">
                         {{ t.views }} / {{ t.created_time }}  作者:{{ t.user().username }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>

templates/topic/two_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <link rel="stylesheet" href="detail.css">
</head>
<body>
        <div class="reveal">
            <span class="title">Blog</span>
        </div>
        <div class="blog-box">
            <span class="title-1">{{ t.title }}</span>
            <span class="content">{{ t.content }}</span>
            <a class="btn" type="submit" display="{{ display }}" href="{{ url_for('topic.delete', id=t.id, token=token) }}">删除</a>
            <form action="{{ url_for('reply.add', tid=t.id, uid=id_user) }}" method="post">
                <textarea class="content" name="content" rows="8" cols="80" placeholder="...内容..."></textarea>
                <button class="btn" type="submit">提交</button>
            </form>
        </div>
        <script type="text/javascript" src="detail.js"></script>
</body>
</html>